### ISSUE TITLE
Failing to deploy artifacts into oss-snapshot-local Access denied ReasonPhrase Forbidden.

### ISSUE THREAD

**Issue by rousef42** [jfrog/build-info#120]
Hi,

I have recently received permission to deploy to the oss.jfrog.org repository. I have been deploying release artifacts to bintray but wanted a place to store snapshot artifacts. I'm getting the following error code.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project root-parent: Failed to deploy artifacts: Could not transfer artifact com.dell.cpsd:root-parent:pom:0.2.6-20170525.193322-1 from/to jfrog-snapshots (https://oss.jfrog.org/artifactory/oss-snapshot-local): Access denied to: https://oss.jfrog.org/artifactory/oss-snapshot-local/com/dell/cpsd/root-parent/0.2.6-SNAPSHOT/root-parent-0.2.6-20170525.193322-1.pom, ReasonPhrase: Forbidden. -> [Help 1]`

Using this configuration
pom.xml

   <groupId>com.dell.cpsd</groupId>
    <artifactId>root-parent</artifactId>
    <version>0.2.6-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Parent Project</name>
    <description>Parent pom for Dell CPSD Symphony</description>
    <url>https://github.com/dellemc-symphony/root-parent</url>

    <licenses>
        <license>
            <name>Eclipse Public License - v 1.0</name>
            <url>http://www.eclipse.org/legal/epl-v10.html</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Frank Rouse</name>
            <email>frank.rouse@dell.com</email>
            <organization>com.dell.cpsd</organization>
            <organizationUrl>https://github.com/rousef42</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:git://github.com/dellemc-symphony/root-parent.git</connection>
        <developerConnection>scm:git:git://github.com/dellemc-symphony/root-parent.git</developerConnection>
        <url>https://github.com/dellemc-symphony/root-parent/tree/master</url>
    </scm>

    <distributionManagement>
        <repository>
            <name>jfrog-release</name>
            <id>jfrog-release</id>
            <url>https://oss.jfrog.org/artifactory/oss-release-local</url>
        </repository>
        <snapshotRepository>
            <name>jfrog-snapshots</name>
            <id>jfrog-snapshots</id>
            <url>https://oss.jfrog.org/artifactory/oss-snapshot-local</url>
        </snapshotRepository>
    </distributionManagement>

settings.xml

`    <servers>
        <server>
            <id>jfrog-release</id>
            <username>rousef42</username>
            <password>xxxx</password>
        </server>
        <server>
            <id>jfrog-snapshots</id>
            <username>rousef42</username>
            <password>xxx</password>
        </server>
    </servers>
`

I have used the credentials from the settings.xml to successfully log into the oss.jfrog.org artifactory site so I assume that is not the problem. When I attempt to manually deploy an artifact using the web site I can upload a file but the target repository drop down menu is blank and the deploy button is always greyed out. 

Any idea why this is not working?

**Comment by eyalbe4** [comment]
@rousef42,
It might be best to keep this space for issues related to the build-info project.
As for the Forbidden message you're getting, my guess is that it is related to the version in the deployment path. Can you try specifying the version tag in the pom?

**Comment by blablanumerodeux** [comment]
any news from 2017 ?

**Comment by eyalbe4** [comment]
Thanks for sharing this @blablanumerodeux! This information may help others.
I'm closing this issue.
