### ISSUE TITLE
using maven-publish gradle plugin creates empty pom files

### ISSUE THREAD

**Issue by mouse256** [jfrog/build-info#138]
When using the new maven-publish plugin instead of the maven plugin, empty pom files are generated when pushing to artifactory. When using the same project and pushing to a local maven repo it works as expected.

Created a small test project: https://github.com/mouse256/artifactory-gradle-tests/tree/master/test1
* module1 is a java-library that uses maven-library: broken
* module1a is a copy that uses maven: works
* module2 is a java application with maven-library: also broken

**Comment by agent8261** [comment]
It's the same for me. Here is a workaround:
```
publishing {
    publications {
        aarPublication(MavenPublication) {
            groupId = SDK_POM_GROUP
            artifactId = ARTIFACT_ID
            version = version

            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')

                configurations.getByName("archives").allDependencies.each {
                    if (it.group != null && (it.name != null || "unspecified".equals(it.name)) && it.version != null) {
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        dependencyNode.appendNode('groupId', it.group)
                        dependencyNode.appendNode('artifactId', it.name)
                        dependencyNode.appendNode('version', it.version)
                    }
                }
            }

            artifact(sourceJar)
            artifact("$buildDir/outputs/aar/${project.getName()}-release.aar")
        }
    }
}
```

**Comment by steven-aerts** [comment]
I have the impression that this is caused at `TaskHelperPublications#checkDependsOnArtifactsToPublish`:

    dependsOn(((MavenPublicationInternal) mavenPublication).getPublishableFiles());

which calls it too early in the process.  So the maven publication will resolve its dependencies before they are specified.
This could be worked around with:

     ((MavenPublicationInternal) mavenPublication).allPublishableArtifacts(this::dependsOn);

This fixes the problem but still uses an internal api.
I think the main problem is that an internal api is used and that the *TODO* in the code should be fixed:

> // TODO: Check how the output files can be extracted without using getPublishableFiles

Also be aware that `allPublishableArtifacts` is rather recent and was previously called `allArtifacts`.  

Wrapping the code which adds (implicitly) the artifacts in enough `afterEveluate` blocks might help you getting around this issue.

**Comment by steven-aerts** [comment]
An easy way to check that you hit this issue, run: `gradle generatePomFileForMavenJavaPublication` with and without the artifactory plugin applied in your `build.gradle` file.

When the content of `build/publications/mavenJava/pom-default.xml` differs between the two runs, you know you hit this issue.
