### ISSUE TITLE
Kotlin DSL Support

### ISSUE THREAD

**Issue by scottroemeschke** [jfrog/build-info#184]
Are there plans to officially support the Kotlin Gradle DSL now that it is 1.0?

https://blog.gradle.org/gradle-kotlin-dsl-release-candidate

instead of having to write code like:

```kotlin
publish(delegateClosureOf<PublisherConfig> {
    repository(delegateClosureOf<GroovyObject> {
      setProperty("repoKey", "libs-release-local")
      setProperty("username", ArtifactoryCredentials.getCredentials(properties))
      setProperty("password", ArtifactoryCredentials.getCredentials(properties))
      setProperty("maven", true)
    })
```

**Comment by clayly** [comment]
Two years passed. Is there anyone? Is this project abandoned or something? We deciding whether we should use Artifactory, and luck of clear documention, broken examples and absence of support for production features like Kotlin DSL looks like bad sign for me.

**Comment by gildor** [comment]
You don't need this plugin to use Artifactory, Artifactory is great solutions itself, but to publish something to it just use standard Gradle publishing plugins, so for maven dependencies just use the standard Gradle maven-publish plugin, which not only works fine for Kotlin DSL, but also supports publishing Gradle Metadata

This plugin always was quite redundant and not very useful

**Comment by clayly** [comment]
> You don't need this plugin to use Artifactory, Artifactory is great solutions itself, but to publish something to it just use standard Gradle publishing plugins, so for maven dependencies just use the standard Gradle maven-publish plugin, which not only works fine for Kotlin DSL, but also supports publishing Gradle Metadata
> 
> This plugin always was quite redundant and not very useful
> 
> If you really want to set some custom Artifactory properties for some reason, just write a custom task with simple POST request, it's easier than use this plugin and it doesn't break normal Gradle publishing flow

I hear it for the first time. This important info absent in documentation:

- https://www.jfrog.com/confluence/display/JFROG/Maven+Artifactory+Plugin
- https://www.jfrog.com/confluence/display/JFROG/Gradle+Artifactory+Plugin

And even worse, all the starting guides and examples uses it:

- https://www.jfrog.com/blog/gitlab-and-artifactory-on-your-mark-get-set-build/
- https://www.jfrog.com/confluence/display/JFROG/QuickStart+Guide%3A+Maven+and+Gradle

And even even worse, none of this examples is working.

You can imagine that this is highly unpleasant experience. In the first place for those articles which everyone who trying to start with Artifactory will use.

Please consider update those examples / documentation / plugin / JFrog CLI.

**Comment by eyalbe4** [comment]
This pull request - 
https://github.com/jfrog/build-info/pull/441 was kindly contributed by @sugarmanz and I believe it will be migrated soon. It adds Kotlin DSL support. 

As for the issues you experienced with the plugin examples, I've just tried some of them and they worked as expected. I'd be happy to assist you using them.
