### ISSUE TITLE
Deprecated method used in Gradle plugin (affects Grade 5+)

### ISSUE THREAD

**Issue by jordanjennings** [jfrog/build-info#203]
When running a Gradle build using the latest Artifactory Gradle plugin (4.9.0) with Gradle 5.0 or greater it prints a warning that deprecated features are being used:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
```

When I re-run with warnings enabled here's the warning:

```
The IvyArtifactRepository.layout(String, Closure) method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the IvyArtifactRepository.patternLayout(Action) method instead.
```

I have tracked down the deprecated usage here:

https://github.com/jfrog/build-info/blob/master/build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy#L105

Please take a look at removing this deprecated usage so we don't get warnings anymore. Thank you!

**Comment by yahavi** [comment]
Thanks for reporting this issue, @jordanjennings.
The alternative for _IvyArtifactRepository.patternLayout()_, [IvyArtifactRepository.patternLayout(Action)](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.repositories.IvyArtifactRepository.html#org.gradle.api.artifacts.repositories.IvyArtifactRepository:patternLayout(org.gradle.api.Action)) is in [incubating](https://docs.gradle.org/current/userguide/feature_lifecycle.html#sec:incubating_state) state and hence still unstable.
Therefore we think its better to wait until it becomes in _public_ state before replacing it.
Please let us know if you encounters any blocker issues with that warning.

**Comment by jordanjennings** [comment]
Kind of silly that Gradle would mark something as deprecated before having a stable alternative. Regardless, thanks for the quick reply. There are no blocking issues with the warning message. Feel free to close this issue unless you want to keep it open for tracking that this gets fixed whenever the replacement method is stable.

**Comment by ryansobol** [comment]
Please don't close this issue! My team is currently subscribed to it so we can be alerted when this issue gets fixed.

**Comment by ljacomet** [comment]
FYI, the new API will [no longer be incubating](https://github.com/gradle/gradle/pull/10040/commits/2f4648f5479d8780741584fd6bc940d48d1b4870#diff-e54fc7fe1c58c692bc7140d9757595a6L215) in Gradle 6.0, without changes to it.
This means it can be safely consumed from Gradle 5.0 onwards.
Removal has been postponed to Gradle 7.0 because of its use here and elsewhere.

**Comment by yahavi** [comment]
@jordanjennings @ryansobol 
Gradle Artifactory plugin 4.11.0 is released.
This release includes this [PR](https://github.com/jfrog/build-info/pull/274) that resolves this issue.
Feel free to upgrade.

**Comment by mjustin** [comment]
Looks like this issue is resolved and can be closed.
