### ISSUE TITLE
Gradle metadata not published by artifactory gradle plugin

### ISSUE THREAD

**Issue by bclozel** [jfrog/build-info#247]
As of Gradle 5.3, we can now [publish Gradle metadata](https://blog.gradle.org/gradle-metadata-1.0) with our build. Right now, one needs to enable this feature with `enableFeaturePreview("GRADLE_METADATA")`.

I'm using Gradle 5.6.1 and artifactory plugin 4.9.8 with a publication setup. The `module.json` are generated during the build (and they can be seen in `build/publications/mavenJava/` for each module. As [advised by Gradle developers](https://discuss.gradle.org/t/feedback-needed-gradle-module-metadata/30842/3) I'm publishing porper software components as well.

You can more details about my setup [here](https://github.com/spring-projects/spring-framework/blob/48934cba1bc1ae6bc5ef6c03b41ca66d428901ab/gradle/publications.gradle#L51-L53) and [here](https://github.com/spring-projects/spring-framework/blob/48934cba1bc1ae6bc5ef6c03b41ca66d428901ab/gradle/spring-module.gradle#L50-L58), but basically:

```groovy
// using a software component in the publication setup
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
			artifact sourcesJar
			artifact javadocJar
		}
	}
}

// publishing the maven publication for each project
artifactoryPublish {
	publications(publishing.publications.mavenJava)
}
```

The build log shows that now both `generateMetadataFileForMavenJavaPublication` and `generatePomFileForMavenJavaPublication` tasks are running before the `artifactoryPublish` task, but the `module.json` is not pushed to the artifact repository by the `artifactoryDeploy` task.

Is this feature supported by the artifactory gradle plugin?
Am I missing an experimental flag or some specific configuration on my side?

**Comment by ljacomet** [comment]
Gradle 6.0 will no longer require the feature preview flag to produce the Gradle Module Metadata as it will become the default.
It would be awesome if that new file was published by this plugin.

**Comment by ansman** [comment]
This is increasingly important as Kotlin Multiplatform requires the `.module` files to be publishes along with the standard POM and binary file.

**Comment by ljacomet** [comment]
I am working on a PR to address this

**Comment by yahavi** [comment]
https://github.com/jfrog/build-info/pull/265 had been merged. Thanks @ljacomet!  
@bclozel, @ansman,
A snapshot is available in `oss.jfrog.org`. To test it, use the following configuration in your `build.gradle` file:
```
buildscript {
    repositories {
        maven { url "https://oss.jfrog.org/oss-snapshot-local" }
        jcenter()
    }
    dependencies {
        classpath(group: 'org.jfrog.buildinfo', name: 'build-info-extractor-gradle', version: '4.9.x-SNAPSHOT')
    }
}
```

We'll appreciate you feedback for that!

**Comment by yahavi** [comment]
@bclozel @ansman
Gradle Artifactory 4.11.0 is released.
This release includes this [PR](https://github.com/jfrog/build-info/pull/265). Thanks @ljacomet!
Feel free to upgrade.

**Comment by bclozel** [comment]
This has been fixed. Thanks!
