### ISSUE TITLE
build-info-api 2.13.11 not on bintray

### ISSUE THREAD

**Issue by algoRhythm99** [jfrog/build-info#251]
It appears build-info-api 2.13.11 didn't get pushed to Bintray?
https://dl.bintray.com/jfrog/jfrog-jars/org/jfrog/buildinfo/build-info-api/

**Comment by eyalbe4** [comment]
@algoRhythm99,
All packages are now available on Bintray.
We'll male sure to publish new Build-Info versions  to Bintray as soon as they ate released.
Thanks
