### ISSUE TITLE
build-info-extractor-gradle breaks with Gradle 6.x when Gradle Module Metadata publication is disabled

### ISSUE THREAD

**Issue by rpalcolea** [jfrog/build-info#284]
Hi folks,

Gradle Module Metadata is a format used to serialize the Gradle component model that was introduced as default in Gradle 6.x. However, still possible to disable this for multiple reasons: https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication

For example

```
tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }
```

When this is disabled, 4.11.0 version of the plugin fails to publish with exceptions such as:

```Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.gradle.api.GradleException: File '/agent/workspace/NEBULA-nebula/subprojects/core/build/nebulatest/netflix.nebula.publishing.NebulaReleasePublishLauncherSpec/publish-a-jar/build/publications/nebulaIvy/module.json' does not exist, and need to be published from publication nebulaIvy```

While debugging found that ivyPublicationInternal.getPublishableArtifacts() has the module.json file on it

```
0 = {ArchiveTaskBasedIvyArtifact_Decorated@16692} "ArchiveTaskBasedIvyArtifact_Decorated testnebulareleasepublish:sources:jar:sources"
1 = {PublishArtifactBasedIvyArtifact_Decorated@17562} "PublishArtifactBasedIvyArtifact_Decorated testnebulareleasepublish:jar:jar:null"
2 = {SingleOutputTaskIvyArtifact@17563} "SingleOutputTaskIvyArtifact ivy:ivy:xml:null"
3 = {SingleOutputTaskIvyArtifact@17564} "SingleOutputTaskIvyArtifact testnebulareleasepublish:json:module:null"
```

This was introduced with https://github.com/jfrog/build-info/pull/265/files. 

Ideally, the plugin shouldn't try to publish files that are not being generated

Opening this ticket for visibility and already gave a heads up to @ljacomet

**Comment by ljacomet** [comment]
That's my mistake. The code should have used the artifacts exposed by the normalized publication for now.
Working on a fix.
