### ISSUE TITLE
Add integration tests for Gradle

### ISSUE THREAD

**Issue by ghale** [jfrog/build-info#302]
#293 introduced some rudimentary integration tests for Gradle.

comments from @yahavi 

> We also had a discussion in my team about the tests.
> As you see, currently we don't have integration tests on build-info-extractor-gradle and we are undoubtedly need them.
> I know you worked very hard on them, but there are issues we have to deal with, before merging the code. Please let me know what you think:
> 
> We use TestNG in our integration tests. From our side, It is not very clever to use 2 test environments. Please switch Spoke to TestNG.
> We run integration tests once for all modules. The integration tests shouldn't download Artifactory OSS. The reason is - In other modules we test many of Artifactory features, including once that doesn't enabled in the OSS. It also take a lot of time to download. The solution is to provide an existing Artifactory details. You can download and start a local Artifactory OSS in you machine and provide its url, username and password to the test as environment variables.
> The good news are - We already have tests infrastructure for all of the above! The integration tests should extend IntegrationTestsBase. In this base class we create and delete local remote and virtual repositories in Artifactory. Additionally, we use this class to create the Artifactory clients.
> If you need a good reference to write integration tests for modules see GoExtractorTest and NpmExtractorTest.
> For more information see also: Building and Testing the Sources.

Comments from @ghale 

> I tried to implement my test using IntegrationTestsBase per your recommendation. The problem is that this class tries to create repositories in Artifactory via the rest API and according to the docs that function requires Artifactory Pro. Running the test against Artifactory OSS gives me an error on that step.
> 
> The fundamental problem here is that it's difficult to contribute anything meaningful to this project without some sort of automated regression testing. In fact, my primary motivation for adding the automated testing in the first place was because I wasn't comfortable doing the refactor in this PR without some regression tests in the first place.
> 
> To use theIntegrationTestsBase framework, it seems like you 1) have to manually download, start and manage an Artifactory instance and 2) that instance needs to be Artifactory Pro. To use the Pro version, you need a trial license key which then means you'll be contacted (repeatedly) by the sales team, which is a strong disincentive for contributing. If you're not working on this project on a regular basis, the chances are you'll have to do this every time.
> 
> Ultimately, I think it would be great if there were an automated way to bootstrap the whole download/start/configure step, but even if it were manual, as long as it's painless, I think it's a step in the right direction. Based on my current understanding, I'm not sure I see a clear path to this with how things are now.
> 
> Some questions related to this:
> 
> Is there a way to get an Artifactory Pro license without signing up for a trial? I think it would be perfectly alright if it expired somewhat aggressively as long as it's easy to get another one for development purposes and would not dump you into the sales pipeline.
>
> Is there a way to enable the rest services in Artifactory OSS (at least enough to enable the testing automation)? This would relieve the need for a Pro license.
>
> Is there another way to implement the test automation in Artifactory OSS without using the rest services?
>
> Is there something about the current state of things that I'm not understanding?

I'm happy to take another stab at contributing some tests here, but I'd like to find a less painful way to do so, if one can be found.

**Comment by rpalcolea** [comment]
+1 for this. Specially when there are potential breaking changes in minor releases, it is necessary to have integration tests.

Hopefully JFrog can come up with a sample artifactory instance that this project could use and also enable contributors to do so. It is difficult to validate any change in local environments without doing publishing and testing out snapshots against other projects/plugins
