### ISSUE TITLE
Gradle plugin does not publish all artifacts

### ISSUE THREAD

**Issue by yahavi** [jfrog/build-info#334]
Using same module name as the root project causes the extractModuleInfo task of the module to not being triggered.
Reproducer with instructions here - https://github.com/yahavi/gradle-deploying-issue

It looks like [builtBy](https://github.com/jfrog/build-info/pull/301/files#diff-b2a12c1b329a701fe714eb55df17d8edR140) does not happen when it already been called once for a project with the same GAV.

@ghale can you please take a look? Thanks!

**Comment by ghale** [comment]
Thanks for reporting this @yahavi.  I've described the cause of the problem and the nature of the fix in https://github.com/jfrog/build-info/pull/336.  Please take a look when you get a chance and let me know if you want any changes.
