### ISSUE TITLE
Support for Gradle's lazy configuration API

### ISSUE THREAD

**Issue by melix** [jfrog/build-info#356]
Currently the plugin is using the legacy "eager" task creation API. While this works, it has a number of drawbacks:

- tasks are created and configured even if they won't be called
- the Artifactory plugin tasks are expensive to create (they, for example, read all system properties at configuration time)
- it's a prerequisite for this plugin to support Gradle's [configuration cache](https://docs.gradle.org/6.6-milestone-3/userguide/configuration_cache.html)

**Expected behavior**

The plugin should use the [configuration avoidance API](https://docs.gradle.org/6.6-milestone-3/userguide/task_configuration_avoidance.html) and [lazy configuration API](https://docs.gradle.org/6.6-milestone-3/userguide/lazy_configuration.html).

An unintented consequence of using the eager creation API is that any build which uses the Artifactory plugin will _not_ be compatible with the configuration cache: even if you only execute `test`, for example, the Artifactory plugin will create a number of tasks and via the build info extractor plugin, read system properties in an unsafe manner.

**Comment by Maragues** [comment]
To give some context, here are some of the issues reported by gradle when trying to use configuration cache

> ./gradlew --configuration-cache help

```
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': registration of listener on 'Gradle.addListener' is unsupported
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:build_listeners
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'sun.java.command'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'gopherProxySet'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'awt.toolkit'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'sun.cpu.isalist'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'sun.jnu.encoding'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'sun.arch.data.model'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'user.variant'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'user.timezone'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'user.country'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'sun.java.launcher'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'sun.boot.library.path'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'http.nonProxyHosts'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'jdk.debug'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin': read system property 'sun.cpu.endian'
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
```

It'd be a great save of build time for many developers if JFrog fixed this ❤️

**Comment by andreya108** [comment]
Why it is labeled as "gradle bug" instead of "used deprecated gradle api, required migration to new api"?

**Comment by rpavliuk** [comment]
Any plans on fixing this?

**Comment by dmeibusch** [comment]
We had to stop using the JFrog plugin for all the reasons noted by the OP. In large multi-project builds, the overheads became too much.

**Comment by Maragues** [comment]
Same for us. The migration was super smooth, less than 1h of work.

**Comment by rpavliuk** [comment]
> Same, we've since migrated to the [maven-publish](https://docs.gradle.org/current/userguide/publishing_maven.html) plugin directly.

any hints or nuances on migration? Or are the main docs straight forward enough?

**Comment by yahavi** [comment]
Dear @melix, @Maragues, @andreya108, @rpavliuk, @dmeibusch, and @Sineaggi,

Thank you for using the Gradle Artifactory plugin. We would like to inform you that we are currently in the process of releasing version 5 of the plugin. This major update involves several changes, including the translation of all Groovy code to Java, migration of the code to a new GitHub repository, and handling deprecations to facilitate maintenance of the plugin.

Once we have completed version 5, our next task is to add support for Gradle Lazy configuration and Configuration cache.

We apologize for the long wait and promise to keep you informed of any further developments.

**Comment by yahavi** [comment]
@melix, @Maragues, @andreya108, @rpavliuk, @dmeibusch, and @Sineaggi 
Gradle Artifactory plugin [5.1.0](https://github.com/jfrog/artifactory-gradle-plugin/releases/tag/5.1.0) is released.
In this version, we added support for task configuration avoidance. See https://github.com/jfrog/artifactory-gradle-plugin/pull/37.

We'd appreciate your feedback on that.

**Comment by rpavliuk** [comment]
@yahavi Thanks a lot! We were waiting for this moment 🙂
