### ISSUE TITLE
`artifactoryDeploy` uses old artifact information

### ISSUE THREAD

**Issue by davidnelson-hms** [jfrog/build-info#383]
**Describe the bug**
After changing the version of my artifact, the `artifactoyDeploy` task attempts to deploy to Artifactory using outdated build info.

This appears to be caused by bad caching introduced in #301. That PR introduced a new task called `extractModuleInfo`, which declares its output but not its input. That causes it to be considered up-to-date if the `moduleInfo.json` file has not changed, even if the input values _have_ changed. So although the `artifactoryPublish` task correctly declares all of its inputs, the module information still ends up being outdated.

**To Reproduce**
Using this `build.gradle` file:
```groovy
plugins {
    id 'java'
    id 'maven-publish'
    id 'com.jfrog.artifactory' version '4.17.2'
}

task("writeSources") {
    doLast {
        file("src/main/java").mkdirs()
        file("src/main/java/TestClass.java").write("class TestClass { }")
    }
}

version = System.getenv("VERSION")
repositories { jcenter() }
tasks.compileJava { dependsOn(writeSources) }

publishing.publications.create("mavenJava", MavenPublication) {
    artifact tasks["jar"]
}

artifactory {
    publish {
        defaults {
            publications "mavenJava"
        }
    }
}
```
1. `VERSION=1.2.3 ./gradlew jar extractModuleInfo`
2. `cat build/moduleInfo.json` -> `"id" : ":art:1.2.3"`
3. `VERSION=7.8.9 ./gradlew jar extractModuleInfo`
4. `cat build/moduleInfo.json` -> `"id" : ":art:1.2.3"`

The `moduleInfo.json` file was not updated with the new version information.
Note that this caching bug also affects the `build-info.json` file, but that is harder to demonstrate without actually performing the publish to a real Artifactory instance.

**Expected behavior**
The publish should only use the current module info, not module info that was collected in previous builds.

**Versions**
- Gradle Artifactory plugin version: 4.17.2
- Operating system: macOS Mojave (10.14.5)
- Artifactory Version: 7.4.3

**Comment by yahavi** [comment]
@davidnelson-hms,
The Gradle Artifactory plugin collects the build info **during** build. In other words, we get the information about artifacts and dependencies only when Gradle downloads dependencies and builds the deployable artifacts - It is impossible to precisely find the build artifacts without building the project. However, we are always open for suggestions and new feature requests.

In order to make the command works for you, simply add the `clean` goal:
```sh
./gradlew clean jar extractModuleInfo
```

Please let me know if this information helped.

**Comment by davidnelson-hms** [comment]
One of Gradle's fundamental value propositions is incremental build. It's literally the first bullet point in the user guide article ["What is Gradle?"](https://docs.gradle.org/current/userguide/what_is_gradle.html#gradle_overview). Needing to run `clean` in order for the build output to be correct violates this fundamental principle. Moreover, if `clean` for some reason is necessary to ensure correct behavior, it should be forced; as it stands the build can _silently_ use the wrong version, which is a very serious bug that needs to be mitigated somehow

If a task cannot accurately predict what its inputs and outputs are, then the correct thing for it to do is to not declare any outputs. That way, it will never be cached, and will always run so it is up-to-date. Doing that might solve the current problem with `extractModuleInfo`.

However, as I said in the issue description, I don't think it is the case that this task cannot be cached correctly, because the `artifactoryPublish` task (which was essentially doing the same work as `extractModuleInfo` prior to #301) declares its inputs and outputs correctly, and does not suffer from the same caching bug. Only when we update our plugin version past 4.13.0, where `extractModuleInfo` was introduced, do we experience this bug.

**Comment by staffanf** [comment]
@yahavi Hello, I got bit by this today and will be downgrading to 4.13.0 which seems to work as expected.
This cost me basically a work day just trying stuff and seeing what works.

No-one using Gradle would expect a clean to be needed in order to publish. Also the plugin no longer detects build changes in the publication like it should. It the source code has changed this should be detected and built automatically or else the incremental support is totally broken.

I suggest you improve your integration tests to make sure incremental changes in code are detected and published as expected.

**Comment by yahavi** [comment]
Thanks for your valuable feedback, @davidnelson-hms @staffanf.
We are taking it seriously and working diligently on resolving this issue for you.

We'll keep you updated.

**Comment by yahavi** [comment]
@davidnelson-hms @staffanf 
Update - I created this [PR](https://github.com/jfrog/build-info/pull/390) to target the issue.
The change forces previous outputs of extractModuleInfo to not be reused, so that this task will never be skipped again.
Read more about `upToDateWhen​` here: https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskOutputs.html#upToDateWhen-groovy.lang.Closure-

**Comment by staffanf** [comment]
@yahavi I'm glad you are on it.
To me using upToDateWhen() tends to indicated that inputs and outputs is not properly defined for a task, int this case extractModuleInfo. If nothing has changed to the previous inputs or outputs, then the task should not have to run again...

**Comment by yahavi** [comment]
Thanks for your feedback @staffanf.
I merged #390 to solve the problem for now.

Regarding the input/output of the task, I suggest advising with @ghale, since he is the one who contributed the task.
@ghale - Can you please provide your inputs? Thanks!

**Comment by ghale** [comment]
It probably makes sense to just leave this task always out-of-date for now.  The input for this task is the `Module` object, which isn't a Gradle-specific object, so adding nested annotations wouldn't make sense.  We'd need to interrogate the `Module` model and then produce something that could be hashed as an input, which is basically what the json serialization does, so the only work we would save by making it up-to-date is the write itself.

Stepping back, the whole point of this task is to share the `Module` info across projects in a parallel-safe way that is compatible with older versions of Gradle.  This is one of the use cases that [build services](https://docs.gradle.org/current/userguide/build_services.html) are designed to solve, but these are only available in Gradle 6+.  Perhaps once support is dropped for older versions of Gradle we could just migrate this functionality to a build service and get rid of these tasks altogether.  For now, maybe we just leave these tasks non-incremental.

**Comment by davidnelson-hms** [comment]
That makes sense to me, @ghale. One question I still have though is why this was not an issue before `extractModuleInfo` was introduced. Previous versions of the task chain were (apparently) able to cache their inputs correctly.

**Comment by davidnelson-hms** [comment]
Thanks for that explanation. To the degree that I understand the problem, I agree that it would not improve performance much to make that task incremental. There is some advantage to making it incremental anyway: my team audits tasks which do no report up-to-date on a second run with no source changes, to make sure that we are not unintentionally degrading performance with cache misses.

That said, most teams do not do that, and even my team doesn't usually audit tasks which perform write operations beyond the local machine (although this experience is causing me to reconsider that). So I'm not too concerned about it.

**Comment by rupebac** [comment]
any idea then when the fix will be released?

**Comment by eyalbe4** [comment]
@rupebac,this will be released by the end of next week, but hopefully sooner.

**Comment by yahavi** [comment]
@davidnelson-hms @staffanf 
Gradle Artifactory plugin 4.18.0 is released - feel free to upgrade.
We'd appreciate your feedback for that!
