### ISSUE TITLE
Pip build info extractor AQL query causes Artifactory to crash

### ISSUE THREAD

**Issue by asoc** [jfrog/build-info#429]
**Describe the bug**
I manage a Jenkins server that uses the Artifactory plugin to integrate with our in-house Artifactory server. With the latest upgrade (3.10.0) I started seeing Artifactory outages after Python builds, and eventually narrowed it down to this seemingly innocous AQL query produced during build info extraction:

```
items.find({"repo": "develop-search-pypi","$or": [
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"parso-0.7.1-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"lxml-4.6.2-cp36-cp36m-manylinux1_x86_64.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"pyvmomi-7.0.1.tar.gz"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"ipython-7.16.1-py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"colorama-0.4.4-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"prompt_toolkit-3.0.8-py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"pexpect-4.8.0-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"requests-2.25.1-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"setuptools-51.1.0.post20201221-py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"traitlets-4.3.3-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"wcwidth-0.2.5-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"lockfile-0.12.2-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"urllib3-1.26.2-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"ipython_genutils-0.2.0-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"pudb-2020.1.tar.gz"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"setproctitle-1.2.1-cp36-cp36m-manylinux1_x86_64.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"idna-2.10-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"decorator-4.4.2-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"chardet-4.0.0-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"six-1.15.0-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"pickleshare-0.7.5-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"sh-1.14.1-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"Pygments-2.7.3-py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"urwid-2.1.2.tar.gz"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"certifi-2020.12.5-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"ptyprocess-0.6.0-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"jedi-0.17.2-py2.py3-none-any.whl"}}]},
  {"$and":[{"path":{"$match":"*"},"name":{"$match":"backcall-0.2.0-py2.py3-none-any.whl"}}]}]}
).include("name", "repo", "path", "actual_sha1", "actual_md5")
```

I ran this query manually through a REST client starting with a single `{"$and": ...}` element and it returns instantly with the correct data. I subsequently ran the query again and again with an increasing amount of the elements and the response came back slower and slower until eventually it just did not return and Artifactory had crashed and was rebooting. 

**After reverting the Jenkins plugin back to 3.9.0 (extractor v2.20.0) the issue disappears.** 
I believe the `PipBuildInfoExtractor.java` changes from #416 are the culprit (even though the real issue is probably on the Artifactory side, not being able to handle the AQL query).

The `develop-search-pypi` repository is structured as follows:

```
(virtual) develop-search-pypi
    ^- (local) develop-search-pypi-local
    ^- (virtual) pypi
        ^- (local) pypi-local
        ^- (remote) _pypi
```

**To Reproduce**

Run above AQL query against repository structure outlined above.

**Expected behavior**

Artifactory does not crash and build info is retrieved in a timely manner.

**Versions**
- Extractor version: 2.21.0
- Jenkins Artifactory plugin version: 3.10.0
- Jenkins operating system: 2.263.1
- Artifactory Version: 7.11.5

**Comment by yahavi** [comment]
Thanks for reporting this issue, @asoc!
We are working on a fix: https://github.com/jfrog/build-info/pull/430. The fix will be included in the next patch version of the Jenkins Artifactory plugin.
We will keep you updated.

**Comment by yahavi** [comment]
@asoc,
The fix is merged to the master branch. 
Following your feedback, we reduced the number of AQL queries for each request to 3. We also added some optimizations.

Here is a snapshot that includes the fix: 
https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.10.x-SNAPSHOT/artifactory-3.10.x-20201224.144314-8.hpi

We'd appreciate your feedback on that!

**Comment by asoc** [comment]
@yahavi snapshot works great, thanks for the quick fix!
