### ISSUE TITLE
JCenter is being sunset, publish java artifacts to Maven Central

### ISSUE THREAD

**Issue by Sineaggi** [jfrog/build-info#472]
**Describe the bug**
JCenter is going away as per https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**To Reproduce**
```
repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jfrog.buildinfo:build-info-extractor-gradle:4.21.0")
}
````

stacktrace

```
   > Could not find org.jfrog.buildinfo:build-info-extractor-gradle:4.21.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jfrog/buildinfo/build-info-extractor-gradle/4.21.0/build-info-extractor-gradle-4.21.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :artifactory-gradle-plugin
```

**Expected behavior**
Expected build-info-extractor dependencies to resolve.

**Additional context**
Would like to see all previously published build-info-* jars published to mavencentral.

**Comment by carltonwhitehead** [comment]
The Gradle version of the plugin seems to be available from the Gradle plugin repository, so this plugin alone doesn't block migration away off of jcenter.

For a groovy build.gradle:
```groovy
buildscript {
    repositories {
        gradlePluginPortal()
    }
}
```
The documentation for this plugin still directs users to include jcenter, so that still requires attention. https://www.jfrog.com/confluence/display/rtf/gradle+artifactory+plugin

**Comment by Sineaggi** [comment]
Looks like this was fixed today, artifacts are available on maven central now https://search.maven.org/artifact/org.jfrog.buildinfo/build-info-extractor-gradle/4.23.4/jar

**Comment by Sineaggi** [comment]
Although the 4.23.4 release is missing from the gradle plugin portal now. https://plugins.gradle.org/plugin/com.jfrog.artifactory is missing 4.23.4
