### ISSUE TITLE
xstream version less than 1.4.16 is vulnerable, need to update xstream version to 1.4.16 

### ISSUE THREAD

**Issue by renjithpk** [jfrog/build-info#486]
Link to the issue: https://github.com/x-stream/xstream/security/advisories/GHSA-hwpc-8xqv-jvj4
This issue blacklisting build-info-extractor-gradle package with security checks in place.

**Comment by yahavi** [comment]
@renjithpk 
Thanks for reporting this issue!
The fix is merged to the master branch and will be available in the next release.
We'll keep you updated.

**Comment by yahavi** [comment]
@renjithpk 
build-info-extractor-gradle 4.24.0 is released and available in Maven Central. This version includes the dependency update to 1.4.16.
Jenkins Artifactory plugin v3.11.0 and the Gradle Artifactory plugin v4.24.0 already include the fix.
Please let us know if there is a another plugin you wish to update to get this dependency update.
