### ISSUE TITLE
All publish tasks fail with: Unrecognized field "slf"

### ISSUE THREAD

**Issue by nstuart-idexx** [jfrog/build-info#506]
**Describe the bug**
Using the gradle artifactory plugin to publish any type of artifact (pom, war, jar) fails with an error and does not publish the artifact. This is against the cloud version of artifactory, `<company>.jfrog.io`

**To Reproduce**
Publish any artifact to a repository in the cloud.

**Expected behavior**
Publishing should succeed with out error.

**Versions**
- Gradle Artifactory plugin version: 4.9.6, 4.18.2, 4.21.0
- Operating system: Linux
- Artifactory Version: Unknown...cloud hosted

**Additional context**
Full error in the build:
Execution failed for task ':artifactoryDeploy'.
13 actionable tasks: 13 executed
> java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "slf" (class org.jfrog.build.client.ArtifactoryUploadResponse), not marked as ignorable (12 known properties: "checksums", "size", "repo", "downloadUri", "path", "statusLine", "created", "errors", "uri", "mimeType", "createdBy", "originalChecksums"])

   at [Source: (org.apache.http.conn.EofSensorInputStream); line: 2, column: 12] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["slf"])

**Comment by gailazar300** [comment]
Thanks for reporting! @nstuart-idexx 
A fix for this bug will be released soon.
PR: https://github.com/jfrog/build-info/pull/502

**Comment by nstuart-idexx** [comment]
Do we have an estimate of when the release will be available? Our build/release pipelines are all broken because the publish tasks fail and I'm not aware of any other work around we can use to get them functioning again.

**Comment by yahavi** [comment]
@nstuart-idexx,
Gradle Artifactory plugin 4.24.4 is released and includes a fix for this issue.
This version is [available](https://mvnrepository.com/artifact/org.jfrog.buildinfo/build-info-extractor-gradle/4.24.4) in Maven Central.
We'd appreciate your feedback on that.

**Comment by yahavi** [comment]
@nstuart-idexx 
Thanks for your feedback.
The official Gradle Artifactory plugin documentation can be found here: https://www.jfrog.com/confluence/display/JFROG/Gradle+Artifactory+Plugin.
To use the plugin from Maven Central add the mavenCentral() repository in the buildscript scope:
```groovy
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "org.jfrog.buildinfo:build-info-extractor-gradle:latest.release"
  }
}
apply plugin: "com.jfrog.artifactory"
```

Please let me know if that helped.

**Comment by nstuart-idexx** [comment]
Thanks, sorry I missed that. We obviously had that classpath block, but I needed to change `latest.release` to the specific version of `4.24.4` in one project, and now the others with `latest.release` are using it as well. Something in our repository setup causing this I guess.

But, the original problem does appear to be solved. Thanks.

**Comment by martinm82** [comment]
Wouldn't it be good to mention in the release notes with which Artifactory version build-info is compatible with. The problem is that this change in the Deploy Artifact API has changed in Artifactory but there are no traces in the release notes of Artifactory nor in the REST API documentation.

See https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-DeployArtifact where it states only:

```
PUT /libs-release-local/my/jar/1.0/jar-1.0.jar
{
"uri": "http://localhost:8081/artifactory/libs-release-local/my/jar/1.0/jar-1.0.jar",
"downloadUri": "http://localhost:8081/artifactory/libs-release-local/my/jar/1.0/jar-1.0.jar",
"repo": "libs-release-local",
"path": "/my/jar/1.0/jar-1.0.jar",
"created": ISO8601 (yyyy-MM-dd'T'HH:mm:ss.SSSZ),
"createdBy": "userY",
"size": "1024", //bytes
"mimeType": "application/java-archive",
"checksums":
{
        "md5" : string,
        "sha1" : string
    },
"originalChecksums":{
        "md5" : string,
        "sha1" : string
    }
}
```
