### ISSUE TITLE
Changed Logging of build-info-extractor-gradle between version  4.23.4 and 4.24.2 

### ISSUE THREAD

**Issue by TheBatOutOfHell** [jfrog/build-info#508]
Hello.
Working with Gradle 7 and using build-info-extractor-gradle plugin for artifactory publish quite some time now. Always used version.latest on it.

Up do at least version 4.23.4 I used to have log output like this

![grafik](https://user-images.githubusercontent.com/85097173/120152161-6fadc080-c1ed-11eb-9d00-8693909962d1.png)

Which was quite convenient to copy and send the war-link to the app engineer.

Now with version.latest 4.24.2 or 4.24.3 are pulled and I have output like 

![grafik](https://user-images.githubusercontent.com/85097173/120152539-e21ea080-c1ed-11eb-8a4d-356149bdffc6.png)

So no full URI anymore and for some reason war building appears twice. Wonder, why this has changed.

Thx
Rob

**Comment by Or-Geva** [comment]
@TheBatOutOfHell, thanks for reporting this issue.
Build-Info 2.26.4 and build-info-extractor-gradle 4.24.4 are released and include a fix for this issue, feel free to upgrade and share your feedback.

**Comment by TheBatOutOfHell** [comment]
@Or-Geva 
Thanks a lot for the quick fix. Just gave it a test after updating dependencies. Lookin good now with
![grafik](https://user-images.githubusercontent.com/85097173/120205705-8f170e80-c22a-11eb-9497-877b89b1f44b.png)
