### ISSUE TITLE
Upload Artifactory Gradle Plugin to Gradle Pluign Portal

### ISSUE THREAD

**Issue by NiazBikbaev** [jfrog/build-info#518]
**Describe the bug**
Plugin has not been updated for a very long time on Gradle Plugin portal (latest version is 4.24.5, on gradle plugin portal 4.21.0)

In order to use latest version, i have to use legacy plugin application:

```kotlin
buildscript {
    dependencies {
        classpath("org.jfrog.buildinfo:build-info-extractor-gradle:4.24.5")
    }
}

apply(plugin = "com.jfrog.artifactory")
```

**Expected behavior**
The expected behavior is that I would be able to use the plugins block in order to apply the plugin:

```kotlin
plugins {
    id("com.jfrog.artifactory") version "4.24.5"
    `maven-publish`
    kotlin("jvm") version "1.5.20"
}
```

**Comment by vojbarzz** [comment]
Hello, 

looks like this update is really needed. We are seeing following error while publishing:
```code
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "slf" (class org.jfrog.build.client.ArtifactoryUploadResponse), not marked as ignorable (12 known properties: "checksums", "size", "repo", "downloadUri", "path", "statusLine", "created", "errors", "uri", "mimeType", "createdBy", "originalChecksums"])```

**Comment by yahavi** [comment]
@NiazBikbaev @vojbarzz 
We created a script that automatically uploads the Gradle plugin to the Gradle plugin portal: https://github.com/jfrog/build-info/blob/master/.github/workflows/gradle.yml
Gradle Artifactory plugin 4.24.12 is already available in the Gradle plugin portal.
We'd appreciate your feedback on that.
