### ISSUE TITLE
Missing dependency in mavenCentral file-specs-java 1.0.0

### ISSUE THREAD

**Issue by haata** [jfrog/build-info#522]
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jfrog.filespecs:file-specs-java:1.0.0.
     Searched in the following locations:
       - https://artifactory.****.com/artifactory/maven/org/jfrog/filespecs/file-specs-java/1.0.0/file-specs-java-1.0.0.pom
       - https://artifactory.****.com/artifactory/maven/org/jfrog/filespecs/file-specs-java/1.0.0/file-specs-java-1.0.0.jar
     Required by:
         project : > org.jfrog.buildinfo:build-info-extractor-gradle:4.24.8 > org.jfrog.buildinfo:build-info-extractor:2.28.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

FAILURE: Build failed with an exception.
```

It seems like the most recent release of build-info-extractor is pulling in a dependency that is not published in mavenCentral.

The only place I can find file-specs-java is from oss.jfrog.org (https://oss.jfrog.org/ui/packages/gav:%2F%2Forg.jfrog.filespecs:file-specs-java?name=file-specs-java&type=packages). Was this an oversight as this indicates the documentation here (https://www.jfrog.com/confluence/display/JFROG/Gradle+Artifactory+Plugin) is no longer correct (cannot used the latest.release for build-info-extractor-gradle).

**Comment by haata** [comment]
https://search.maven.org/artifact/org.jfrog.filespecs/file-specs-java

Why does mavenCentral even allow this?

**Comment by spartanhooah** [comment]
This is breaking our builds. Going to have to pin an earlier version of `build-info-extractor-gradle`

**Comment by DanielJRutledge** [comment]
Everything's broken for us as well; was this dependency supposed to make into mavenCentral?

**Comment by prudnitskiy** [comment]
Any solution for it? We have this issue also

**Comment by spartanhooah** [comment]
I was able to specify `classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.24.5"` and my build worked.

**Comment by haata** [comment]
More info

https://search.maven.org/artifact/org.jfrog.filespecs/file-specs-java <- Does not exist and is required by https://search.maven.org/artifact/org.jfrog.buildinfo/build-info-extractor/2.28.2/jar

**Comment by yahavi** [comment]
@haata @prudnitskiy @DanielJRutledge @spartanhooah
Thanks for reporting this issue. 
The build-info uses https://releases.jfrog.io/artifactory/oss-releases repository to resolve the new [file-spec-java](https://github.com/jfrog/file-specs-java) library. Unfortunately, Gradle plugins are not allowed to download dependencies from this repository. Therefore the solution is, as @haata said, to publish `file-spec-java` to Maven Central.

We are working on publishing this library to Maven Central. Here is the PR which should resolve this issue: https://github.com/jfrog/file-specs-java/pull/7.

As a workaround, you can downgrade to Gradle Artifactory plugin `4.24.5`:

```gradle
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.24.5"
  }
}
apply plugin: "com.jfrog.artifactory"
```

We're terribly sorry for this coincidence.

**Comment by yahavi** [comment]
@haata @prudnitskiy @DanielJRutledge @spartanhooah
Gradle Artifactory plugin 2.28.3 is released. This version includes a fix for this issue.
We'd appreciate your feedback on that.

**Comment by DanielJRutledge** [comment]
The new one seems to work; though we had to introduce a new exception for the file-specs-java artifacts, as the licenses are not picked up for a couple days by Xray. It would be helpful to know whether you guys plan to introduce more artifact types.

We have an issue open with Jfrog support about the licenses for these artifacts not being picked up locally.
