### ISSUE TITLE
403 for build-info-extractor-gradle-4.15.2-uber.jar

### ISSUE THREAD

**Issue by sebasira** [jfrog/build-info#547]
I'm using jFrog CLI v1.39.7 to upload an Android `.aar` library to Artifactory (because newer version do not support yet) and it was working fine, but now I get this message:

```
$ ./jfrog rt gradle-config --use-wrapper=true --repo-resolve=$GRADLE_REPO_KEY --server-id-resolve=Default-Server --repo-deploy=$GRADLE_REPO_KEY --server-id-deploy=Default-Server # collapsed multi-line command
[Info] gradle build config successfully created.
[Info] Downloading bintray/jcenter/org/jfrog/buildinfo/build-info-extractor-gradle/4.15.2/build-info-extractor-gradle-4.15.2-uber.jar
[Error] 403 Forbidden 
ERROR: Job failed: exit code 1
```

Have you lock the access to that file?

**Comment by eyalbe4** [comment]
Thanks for asking this question @sebasira.
The issue you see is probably the result of the sunset of Bintray. Please go ahead and upgraded your JFrog CLI version resolve the issue. 
Please let us know if you have follow up questions.

**Comment by sebasira** [comment]
Thanks for your fast reply, I was assuming that but I wanted confirmation.

Sadly I can not update to the any version of jFrog CLI above1.39.7, because since v1.40 Android **.aar** artifacts are not uploaded.

Maybe you can take a look at this to help me out: https://github.com/jfrog/jfrog-cli/issues/880. Which is the same as #406, but you'll find more info in the jFrog CLI repo.

Thank you 🙏

**Comment by DanielJRutledge** [comment]
@sebasira I saw this behavior with 1.40, you can override the download target of these jars with

`export JFROG_CLI_JCENTER_REMOTE_SERVER=artifactory
 export JFROG_CLI_JCENTER_REMOTE_REPO=maven-repo`

Where in this case artifactory is the repo defined with my `rt config` command and `maven-repo` is a repo that has jcenter available as a remote repo in its resources.

**Comment by DanielJRutledge** [comment]
Yes, you'd be running before your gradle config. In your case, you'd be looking at

```export JFROG_CLI_JCENTER_REMOTE_SERVER=Default-Server```
```export JFROG_CLI_JCENTER_REMOTE_REPO=$GRADLE_REPO_KEY```

You'd be sending it through the same repo you using for your build config. This assumes you have jcenter in your gradle repo.

**Comment by sebasira** [comment]
Thank you very much! Now I can upload artifacts to Artifactory again! 

I'm closing this issue
