### ISSUE TITLE
gradle artifactory plugin - resolve.ivy.mavenCompatible=true does not convert dots to paths for ivyPaths

### ISSUE THREAD

**Issue by hborham** [jfrog/build-info#55]
I noticed the resolver configuration does not convert dots to paths when setting mavenCompatible = true when searching for ivy files. As a consequence the artifact is retrieved but the ivy.xml is not and thus none of the configuration dependencies are downloaded.

Example:

```
artifactory {

    contextUrl = "${project.getProperty('artifactory.contextUrl')}"  

    resolve {
        repository {
            repoKey = 'someRepo'
            username = "someUser"
            password = "somePassword"
            maven = true
            ivy {
                mavenCompatible = true
                ivyLayout = '[organization]/[module]/[revision]/ivy.xml'
                artifactLayout = '[organization]/[module]/[revision]/[module]-[revision](-[classifier]).[ext]'
            }
        }
    }
}
```

Resolution for ivyLayout works fine in the case where I hardcode the organization in ivyLayout.

Publishing seems to work fine with mavenCompatible = true

**Comment by hborham** [comment]
Tried the following combinations:

* gradle 2.4 and org.jfrog.buildinfo:build-info-extractor-gradle:3.1.1
* gradle 2.4 and org.jfrog.buildinfo:build-info-extractor-gradle:3.0.3

**Comment by doit-ceo** [comment]
Yes, we are facing the same issue , we have to / the org to make work !!
compile (group: 'org/company', name: 'some-name' ,version: '1.0.16', classifier: 'master', ext: 'jar')

**Comment by reitzig** [comment]
Still seeing this!

Gradle 4.0, org.jfrog.buildinfo:build-info-extractor-gradle:4.6.2

Just cost us two man days debugging everything from top to bottom, only to find this sillyness. -.-

**Comment by barbelity** [comment]
@hborham @doit-ceo @reitzig 
We have decided to deprecate the resolve section inside the **artifactory** closure. We therefore recommend using:
`repositories {
  	ivy {
		url "${project.getProperty('artifactory.contextUrl')}/someRepo"
 		credentials {
 			username "someUser"
			password "somePassword"
		}
		layout "pattern", {
    			ivy "[organization]/[module]/[revision]/ivy.xml"
        		artifact "[organization]/[module]/[revision]/[module]-[revision](-[classifier]).[ext]"
        		m2compatible = true
    		}
    }
}`
Following this deprecation, we are not planning to fix this issue - however, we are not going to remove this functionality.
We updated the Gradle Artifactory Plugin [documentation] (https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin#GradleArtifactoryPlugin-UsingtheArtifactoryPluginDSL) accordingly.
We will soon update the [gradle-examples](https://github.com/JFrogDev/project-examples/tree/master/gradle-examples) with the new recommendations.
