### ISSUE TITLE
Build info extractors no longer applying publishing repository from Teamcity Artifactory plugin

### ISSUE THREAD

**Issue by DanielJRutledge** [jfrog/build-info#592]
**Describe the bug**
We rely on the publishing repository being applied from the Teamcity Artifactory plugin, overriding the setting in the project's build.gradle. As of 4.25.3, it seems as though the Publishing repository is no longer being applied from the Teamcity Artifactory plugin.

**To Reproduce**
Set a repository in the Teamcity Artifactory plugin, overriding the setting in the project's build.gradle.

`artifactory {
    contextUrl = "${artifactoryBase}"
    ...
    publish {
      repository {
        repoKey = isRelease ? 'maven-release' : 'maven-dev'
      }
    defaults {
        publications ('ALL_PUBLICATIONS')
    }
  }
}`

**Expected behavior**
Historically, the setting in the Teamcity plugin has overridden the setting in build.gradle.

**Versions**
- Extractor version: 4.25.3
- Operating system: RHEL 7
- Artifactory Version: 7.27.9

**Comment by Or-Geva** [comment]
Thanks for reporting this issue @DanielJRutledge.
I have created [PR](https://github.com/jfrog/build-info/pull/590)) to fix this issue. As a temporary workaround, please downgrade to version 4.25.2.
Once the fix will get released, I will update this thread.

**Comment by Or-Geva** [comment]
@DanielJRutledge, Gradle extractor 4.25.4 is released and it includes the fix for your issue.
Feel free to upgrade share your feedback.

**Comment by DanielJRutledge** [comment]
Yes, 4.25.4 addressed the issue.
