### ISSUE TITLE
ConfigureUtil deprecation reported on Gradle 7.6+

### ISSUE THREAD

**Issue by bwmeier** [jfrog/build-info#708]
**Describe the bug**
ConfigureUtil has been deprecated and will be removed in Gradle 9.0.  This deprecation warning is reported when running the plugin in Gradle 7.6+.  See the groovy doc for ConfigureUtil at https://docs.gradle.org/7.6/javadoc/org/gradle/util/ConfigureUtil.html for the deprecation information and a way to code the plugin to resolve the issue.

**To Reproduce**
Execute a build containing the plugin in Gradle 7.6 or greater with `--warning-mode all`.

**Expected behavior**
The plugin configures and executes without deprecation warnings.

**Stack Trace**

> > Configure project :
> The org.gradle.util.ConfigureUtil type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.6/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations
> 	at org.gradle.util.ConfigureUtil.logDeprecation(ConfigureUtil.java:216)
> 	at org.gradle.util.ConfigureUtil.configureUsing(ConfigureUtil.java:167)
> 	at org.gradle.util.ConfigureUtil$configureUsing.call(Unknown Source)
> 	at org.jfrog.gradle.plugin.artifactory.dsl.ArtifactoryPluginConvention.artifactory(ArtifactoryPluginConvention.groovy:25)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
> 	at org.gradle.internal.extensibility.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:308)
> 	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:36)
> 	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:135)
> 	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
> 	at build_1ievt9i82cdx3beak2wey5vd8.run(gradle-plugins\build.gradle:115)
> 

**Versions**
- Gradle Version 7.6/8.0
- Gradle Artifactory plugin version: 4.31.3
- Operating system: Windows 10 / WSL 2

**Comment by ErwanLeroux** [comment]
Is it really a bug on gradle side ? They deprecated a class and provided a replacement.

**Comment by yahavi** [comment]
Hey @bwmeier & @ErwanLeroux,
Thanks for letting us know about this problem.

We're on it and actively working to fix it. You can check out our progress at this link: https://github.com/jfrog/artifactory-gradle-plugin/pull/72

We'll keep you in the loop with updates.

**Comment by ErwanLeroux** [comment]
Thank you for the update !

**Comment by yahavi** [comment]
@ErwanLeroux @bwmeier 
Version 5.1.10 of the Gradle Artifactory plugin has just been released. In this release, we've made the transition from Gradle conventions to extensions. If you'd like to, please consider upgrading, and we'd love to hear your feedback on this update.

**Comment by ErwanLeroux** [comment]
@yahavi Hello, I don't see deprecation warning anymore when using the 5.1.10 version, thank you !
