### ISSUE TITLE
Cannot turn publishing artifacts off

### ISSUE THREAD

**Issue by ojecborec** [jfrog/build-info#776]
**Describe the bug**
Trying to build Maven project without publishing artifacts to Artifactory. Looks like `-Dartifactory.publish.artifacts=false` parameter is being ignored. Has this parameter changed recently?

**To Reproduce**
JFrog CLI 2.52.8

```
jf mvn install -f pom.xml -Dartifactory.publish.artifacts=false -Dartifactory.publish.buildInfo=false --build-name=MyProject --build-number=20230103.1
15:44:25 [🔵Info] Downloading JFrog's Dependency from https://releases.jfrog.io/artifactory/oss-release-local/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.9/build-info-extractor-maven3-2.41.9-uber.jar
[pool-6-thread-2] INFO org.jfrog.build.extractor.maven.ArtifactoryManagerBuilder - [pool-6-thread-2] Deploying artifact: https://.../my-project.jar
...
```

I can only exclude publishing artifacts if I use `mvn package` instead of `mvn install` which is something I'm trying to avoid.

**Expected behavior**
JFrog CLI 2.51.1 works as expected. See the log entry: _deploy artifacts set to false, artifacts will not be deployed_

```
jf mvn install -f pom.xml -Dartifactory.publish.artifacts=false -Dartifactory.publish.buildInfo=false --build-name=MyProject --build-number=20230103.1
15:28:11 [🔵Info] Downloading JFrog's Dependency from https://releases.jfrog.io/artifactory/oss-release-local/org/jfrog/buildinfo/build-info-extractor-maven3/2.41.7/build-info-extractor-maven3-2.41.7-uber.jar
[main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: deploy artifacts set to false, artifacts will not be deployed...
```

**Versions**
- Maven Artifactory plugin version: 
- Operating system: Debian 12.2
- Artifactory CLI Version: 2.52.8
- build-info-extractor-maven3-2.41.9-uber.jar

**Comment by yahavi** [comment]
@ojecborec 
Thanks for reporting this issue.
We already created #775 to fix it.
You can subscribe https://github.com/jfrog/jfrog-cli/issues/2373 for updates.

**Comment by ojecborec** [comment]
Thank you for letting me know. I'm closing this issue.
